### ISSUE TITLE
Create 2 Repositories with unique Chicken Recipe

### ISSUE THREAD

**Issue by AdiKhaparkar** [AdityaGavranChickenPoultryCenter/Quail#2]
"आपल्या पाठीशी आणि प्रेमाशी घेतलेल्या जणीवर आधारित, आमच्या फूडी चॅनलवर आपले स्वागत आहे! येथे आपल्याला मराठीतील विविध आणि खास रेसिपींची जमवणारी जगावणं आहे.

आपण येथे पाहीले जाणार आहोत:

पारंपारिक मराठी रेसिपींची माहिती आणि त्यांचे पदार्थ
जवळजवळ सर्व जण वेगळ्या तारखेवारींची मराठी रेसिपींची आवडती आणि प्रेम
सुप्रसिद्ध खाद्यांची बातमी आणि त्यांच्या तयारीचा नुस्खा
अनुभवी मराठी रसोईप्रदेशांना येणारे सूत्रे आणि सल्ले
चांगल्या अनुभवांच्या साथी आरोग्यदायी आणि घरगुती प्राण्यांच्या पर्यायी खाद्यांची चर्चा
आपल्या मराठी फूडी चॅनलवर सर्वाना आपले वेगवेगळे रसिकता अनुभवण्याची संधी दिली जाते. आमच्या अनुसंधानाचा उपयोग करून, आपल्याला जवळजवळ सर्व प्रकारचे आहार आणि रेसिपींची मराठीतील बातमी देण

**Comment by Shrirang-joshi17198** [comment]
mutton chi bajji kashi banavtat yawar ek video banwawa
